VERSION --shell-out-anywhere 0.6

# renovate datasource=crate depName=cargo-outdated
ARG CRATE_VERSION=0.17.0
ARG CRATE_NAME=cargo-outdated

IMPORT ../rust-binaries

all:
    BUILD rust-binaries+all --CRATE_VERSION=$CRATE_VERSION --CRATE_NAME=$CRATE_NAME --INSTALL_ARGS="--features vendored-openssl"
