VERSION --shell-out-anywhere 0.6

# renovate datasource=crate depName=cargo-audit
ARG CRATE_VERSION=0.17.4
ARG CRATE_NAME=cargo-audit

IMPORT ../rust-binaries

all:
    BUILD rust-binaries+all --CRATE_VERSION=$CRATE_VERSION --CRATE_NAME=$CRATE_NAME


