VERSION --shell-out-anywhere 0.6

# renovate datasource=crate depName=cargo-udeps
ARG CRATE_VERSION=0.1.35
ARG CRATE_NAME=cargo-udeps

IMPORT ../rust-binaries

all:
    BUILD rust-binaries+all --CRATE_VERSION=$CRATE_VERSION --CRATE_NAME=$CRATE_NAME


