VERSION --shell-out-anywhere 0.6

# renovate datasource=crate depName=cargo-pants
ARG CRATE_VERSION=0.4.33
ARG CRATE_NAME=cargo-pants

IMPORT ../rust-binaries

all:
    BUILD rust-binaries+all --CRATE_VERSION=$CRATE_VERSION --CRATE_NAME=$CRATE_NAME \
    --INSTALL_ARGS="--features vendored-openssl --git https://github.com/jaysonsantos/cargo-pants --branch enable-vendored-ssl"
