VERSION --shell-out-anywhere 0.6

# renovate datasource=crate depName=cargo-deny
ARG CRATE_VERSION=0.15.1
ARG CRATE_NAME=cargo-deny

IMPORT ../rust-binaries

all:
    BUILD rust-binaries+all --CRATE_VERSION=$CRATE_VERSION --CRATE_NAME=$CRATE_NAME
