VERSION --shell-out-anywhere 0.6
FROM ghcr.io/graalvm/graalvm-ce:ol9-java17
ARG MOD_ID
ARG MOD_VERSION
ARG NAME
ARG TARGETARCH
ARG IS_BETA
ARG name_suffix="$(if [ $IS_BETA = '1' ]; then echo '-beta'; fi)"

install:
    ENV suffix=$(test ${TARGETARCH} = 'arm64' && echo arm/ || true)
    ENV DOWNLOAD_URL=https://api.modpacks.ch/public/modpack/${MOD_ID}/${MOD_VERSION}/server/${suffix}linux
    RUN echo Downloading from ${DOWNLOAD_URL}
    RUN curl --fail -sLo installer ${DOWNLOAD_URL} && chmod +x installer
    RUN ./installer ${MOD_ID} ${MOD_VERSION} --nojava --auto --path /mc
    RUN rm -rf /installer /mc/jre
    WORKDIR /mc
    RUN echo eula=true > eula.txt
    RUN sed -i'' 's/^"jre.[^\"]*/exec "java/' ./start.sh
    RUN sed -i'' 's/ -jar / $JAVA_OPTIONS -jar /' ./start.sh
    SAVE ARTIFACT /mc

image:
    FROM ghcr.io/graalvm/graalvm-ce:ol9-java17
    COPY +install/mc /mc
    WORKDIR /mc
    CMD exec sh ./start.sh
    EXPOSE 25565
    VOLUME /mc/world
    SAVE IMAGE --push ghcr.io/jaysonsantos/bunderwar:${NAME}${name_suffix}-latest
    SAVE IMAGE --push ghcr.io/jaysonsantos/bunderwar:${NAME}${name_suffix}-${MOD_VERSION}

all:
    BUILD --platform=linux/amd64 --platform=linux/arm64 +image

# The -v2 targets use the installer of api.feed-the-beast.com. Packs that are not in api.modpacks.ch need them.
install-v2:
    ARG JAVA_RELEASE=21
    FROM ghcr.io/graalvm/graalvm-community:${JAVA_RELEASE}
    ENV suffix=$(test ${TARGETARCH} = 'arm64' && echo arm/ || true)
    ENV DOWNLOAD_URL=https://api.feed-the-beast.com/v1/modpacks/public/modpack/${MOD_ID}/${MOD_VERSION}/server/${suffix}linux
    RUN echo Downloading from ${DOWNLOAD_URL}
    RUN curl --fail -sLo installer ${DOWNLOAD_URL} && chmod +x installer
    RUN ./installer -pack ${MOD_ID} -version ${MOD_VERSION} -auto -force -accept-eula -no-java -no-colours -dir /mc
    RUN rm -rf /installer /mc/*-installer.jar.log
    WORKDIR /mc
    RUN echo eula=true > eula.txt
    RUN sed -i'' 's/^java /exec java $JAVA_OPTIONS /' ./run.sh
    RUN grep -q '^exec java \$JAVA_OPTIONS ' ./run.sh
    SAVE ARTIFACT /mc

image-v2:
    ARG JAVA_RELEASE=21
    FROM ghcr.io/graalvm/graalvm-community:${JAVA_RELEASE}
    COPY (+install-v2/mc --JAVA_RELEASE=$JAVA_RELEASE) /mc
    WORKDIR /mc
    CMD exec sh ./run.sh
    EXPOSE 25565
    VOLUME /mc/world
    SAVE IMAGE --push ghcr.io/jaysonsantos/bunderwar:${NAME}${name_suffix}-latest
    SAVE IMAGE --push ghcr.io/jaysonsantos/bunderwar:${NAME}${name_suffix}-${MOD_VERSION}

all-v2:
    ARG JAVA_RELEASE=21
    BUILD --platform=linux/amd64 --platform=linux/arm64 +image-v2 --JAVA_RELEASE=$JAVA_RELEASE
