VERSION --shell-out-anywhere 0.6

# renovate datasource=crate depName=sqlx-cli
ARG CRATE_VERSION=0.8.6
ARG CRATE_NAME=sqlx-cli

IMPORT ../rust-binaries

all:
    BUILD rust-binaries+all \
    --CRATE_VERSION=$CRATE_VERSION \
    --CRATE_NAME=$CRATE_NAME \
    --INSTALL_ARGS="--no-default-features --features rustls,postgres,mysql"
