VERSION --shell-out-anywhere 0.6
FROM rust:1-buster
ARG CRATE_VERSION
ARG CRATE_NAME
ARG TARGETARCH

install:
    RUN --mount=type=cache,target=/usr/local/cargo/registry cargo install --locked ${CRATE_NAME} --version ${CRATE_VERSION}
    RUN find /usr/local/cargo/bin
    SAVE ARTIFACT /usr/local/cargo/bin
    SAVE IMAGE --push ghcr.io/jaysonsantos/bunderwar:earthly-crates-cache

image:
    FROM debian:buster-slim
    COPY +install/ /usr/local/cargo/bin
    CMD ["/usr/local/cargo/bin/${CRATE_NAME}"]
    SAVE IMAGE --push ghcr.io/jaysonsantos/bunderwar:${CRATE_NAME}-${CRATE_VERSION}

all:
    BUILD --platform=linux/amd64 --platform=linux/arm64 +image
