VERSION --shell-out-anywhere 0.6

# renovate datasource=crate depName=sccache
ARG CRATE_VERSION=0.13.0
ARG CRATE_NAME=sccache

IMPORT ../rust-binaries

all:
    BUILD rust-binaries+all --CRATE_VERSION=$CRATE_VERSION --CRATE_NAME=$CRATE_NAME --INSTALL_ARGS="--features vendored-openssl"
